// Sign In

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

// Sign Up

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

/////// Card Section

export const GET_FIRESTORE_CARDS = "GET_FIRESTORE_CARDS";
export const GET_FIRESTORE_CARDS_SUCCESS = "GET_FIRESTORE_CARDS_SUCCESS";
export const GET_FIRESTORE_CARDS_FAIL = "GET_FIRESTORE_CARDS_FAIL";

export const UPDATE_FIRESTORE_CARD = "UPDATE_FIRESTORE_CARD";
export const UPDATE_FIRESTORE_CARD_SUCCESS = "UPDATE_FIRESTORE_CARD_SUCCESS";
export const UPDATE_FIRESTORE_CARD_FAIL = "UPDATE_FIRESTORE_CARD_FAIL";

export const UPDATE_CURRENT_CARD = "UPDATE_CURRENT_CARD";
export const UPDATE_CURRENT_CARD_SUCCESS = "UPDATE_CURRENT_CARD_SUCCESS";
export const UPDATE_CURRENT_CARD_FAIL = "UPDATE_CURRENT_CARD_FAIL";

export const DELETE_CARD = "UPDATE_CARD";
export const DELETE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const DELETE_CARD_FAIL = "UPDATE_CARD_FAIL";

export const GET_IMAGE = "GET_IMAGE";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAIL = "GET_IMAGE_FAIL";

// UI

export const UPDATE_SHOW_ANSWER = "UPDATE_SHOW_ANSWER";
export const UPDATE_SHOW_ANSWER_SUCCESS = "UPDATE_SHOW_ANSWER_SUCCESS";
export const UPDATE_SHOW_ANSWER_FAIL = "UPDATE_SHOW_ANSWER_FAIL";

export const UPDATE_SHOW_DEFINITION = "UPDATE_SHOW_DEFINITION";
export const UPDATE_SHOW_DEFINITION_SUCCESS = "UPDATE_SHOW_DEFINITION_SUCCESS";
export const UPDATE_SHOW_DEFINITION_FAIL = "UPDATE_SHOW_DEFINITION_FAIL";
