// Sign In

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

// Sign Up

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

/////// Card Section

export const GET_FIRESTORE_CARDS_CARDS = "GET_FIRESTORE_CARDS_CARDS";
export const GET_FIRESTORE_CARDS_SUCCESS = "GET_FIRESTORE_CARDS_SUCCESS";
export const GET_FIRESTORE_CARDS_FAIL = "GET_FIRESTORE_CARDS_FAIL";

export const UPDATE_FIRESTORE_CARD = "UPDATE_FIRESTORE_CARD";
export const UPDATE_FIRESTORE_CARD_SUCCESS = "UPDATE_FIRESTORE_CARD_SUCCESS";
export const UPDATE_FIRESTORE_CARD_FAIL = "UPDATE_FIRESTORE_CARD_FAIL";

export const UPDATE_CURRENT_CARD = "UPDATE_CURRENT_CARD";
export const UPDATE_CURRENT_CARD_SUCCESS = "UPDATE_CURRENT_CARD_SUCCESS";
export const UPDATE_CURRENT_CARD_FAIL = "UPDATE_CURRENT_CARD_FAIL";

export const DELETE_CARD = "UPDATE_CARD";
export const DELETE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const DELETE_CARD_FAIL = "UPDATE_CARD_FAIL";

export const GET_IMAGES = "GET_IMAGES";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL";
