// Sign In

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

// Sign Up

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

/////// Card Section

export const GET_FIRESTORE_CARDS = "GET_FIRESTORE_CARDS";
export const GET_FIRESTORE_CARDS_SUCCESS = "GET_FIRESTORE_CARDS_SUCCESS";
export const GET_FIRESTORE_CARDS_FAIL = "GET_FIRESTORE_CARDS_FAIL";

export const UPDATE_FIRESTORE_CARD_GRADE = "UPDATE_FIRESTORE_GRADE_CARD";
export const UPDATE_FIRESTORE_CARD_GRADE_SUCCESS = "UPDATE_FIRESTORE_CARD_GRADE_SUCCESS";
export const UPDATE_FIRESTORE_CARD_GRADE_FAIL = "UPDATE_FIRESTORE_CARD_GRADE_FAIL";

export const UPDATE_FIRESTORE_CARD_CONTENT = "UPDATE_FIRESTORE_CARD_CONTENT";
export const UPDATE_FIRESTORE_CARD_CONTENT_SUCCESS = "UPDATE_FIRESTORE_CARD_CONTENT_SUCCESS";
export const UPDATE_FIRESTORE_CARD_CONTENT_FAIL = "UPDATE_FIRESTORE_CARD_CONTENT_FAIL";

export const UPDATE_CURRENT_CARD = "UPDATE_CURRENT_CARD";
export const UPDATE_CURRENT_CARD_SUCCESS = "UPDATE_CURRENT_CARD_SUCCESS";
export const UPDATE_CURRENT_CARD_FAIL = "UPDATE_CURRENT_CARD_FAIL";

export const DELETE_CARD = "UPDATE_CARD";
export const DELETE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const DELETE_CARD_FAIL = "UPDATE_CARD_FAIL";

export const GET_IMAGE = "GET_IMAGE";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAIL = "GET_IMAGE_FAIL";

// UI

export const UPDATE_SHOW_ANSWER = "UPDATE_SHOW_ANSWER";
export const UPDATE_SHOW_ANSWER_SUCCESS = "UPDATE_SHOW_ANSWER_SUCCESS";
export const UPDATE_SHOW_ANSWER_FAIL = "UPDATE_SHOW_ANSWER_FAIL";

export const UPDATE_SHOW_DEFINITION = "UPDATE_SHOW_DEFINITION";
export const UPDATE_SHOW_DEFINITION_SUCCESS = "UPDATE_SHOW_DEFINITION_SUCCESS";
export const UPDATE_SHOW_DEFINITION_FAIL = "UPDATE_SHOW_DEFINITION_FAIL";

export const GET_FORVO_AUDIO = "GET_FORVO_AUDIO";
export const GET_FORVO_AUDIO_SUCCESS = "GET_FORVO_AUDIO_SUCCESS";
export const GET_FORVO_AUDIO_FAIL = "GET_FORVO_AUDIO_FAIL";

export const UPDATE_VIDEO_PAUSED = "UPDATE_VIDEO_PAUSED";
export const UPDATE_VIDEO_PAUSED_SUCCESS = "UPDATE_VIDEO_PAUSED_SUCCESS";
export const UPDATE_VIDEO_PAUSED_FAIL = "UPDATE_VIDEO_PAUSED_FAIL";


